[package]
name = "alexandria"
version = "0.1.0"
authors = ["Jack Maloney <jmmaloney4@gmail.com>"]

[dependencies]
clap = "2.32.0"
serde = "1.0"
serde_derive = "1.0"
ring = "0.13"

[dependencies.rusqlite]
version = "0.15.0"
features = ["bundled"]